This Question source https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [2]:
#1 Import numpy as np and see the version
import numpy as np
import time

print("Numpy version : ", np.__version__)
print("Numpy git_version : ", np.__git_version__)

def gt():
    start = time.time()
    start_cpu = time.process_time() 
    return start,start_cpu



Numpy version :  1.23.2
Numpy git_version :  21cacafbeeff812cf49ca0102d1dd582b6d77e2b


In [3]:
# 2. How to create a 1D array?

# Difficulty Level: L1

# Q. Create a 1D array of numbers from 0 to 9

np.arange(10)
start_time = time.time()
print("--- %.7s seconds ---" % ((time.time() - start_time)))

--- 0.00100 seconds ---


In [4]:
# 3. How to create a boolean array?

# Difficulty Level: L1

# Q. Create a 3×3 numpy array of all True’s

print(np.full((3,3), True, dtype = bool))
print()
print(np.ones((3,3), dtype=bool))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# 4. How to extract items that satisfy a given condition from 1D array?

# Difficulty Level: L1

# Q. Extract all odd numbers from arr

# Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired output:

#> array([1, 3, 5, 7, 9])

# ============ ANSWER ============ #

odd = arr%2!=0
arr[odd]

# arr[arr%2==1] same


array([1, 3, 5, 7, 9])

In [6]:
# 5. How to replace items that satisfy a condition with another value in numpy array?

# Difficulty Level: L1

# Q. Replace all odd numbers in arr with -1

# Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# ============ ANSWER ============ #
arr[arr%2==1] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# 6. How to replace items that satisfy a condition without affecting the original array?

# Difficulty Level: L2

# Q. Replace all odd numbers in arr with -1 without changing arr

# Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired Output:

# out
# #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# #>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ============ ANSWER ============ #

out = arr.copy()
out[out%2==1] = -1
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
# 7. How to reshape an array?

# Difficulty Level: L1

# Q. Convert a 1D array to a 2D array with 2 rows

# Input:

array = np.arange(10)

# #> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired Output:

# #> array([[0, 1, 2, 3, 4],
# #>        [5, 6, 7, 8, 9]])

# ============ ANSWER ============ #

array.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# 8. How to stack two arrays vertically?

# Difficulty Level: L2

# Q. Stack arrays a and b vertically

# Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

# ============ ANSWER ============ #

print("Method 1 \n",np.concatenate([a,b], axis = 0))
print("Method 2 \n",np.vstack([a,b]))
print("Method 3 \n",np.r_[a,b])


Method 1 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Method 2 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Method 3 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
# 9. How to stack two arrays horizontally?

# Difficulty Level: L2

# Q. Stack the arrays a and b horizontally.

# Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

# Desired Output:

# #> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
# #>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

print("a : ",a)
print("b : ",b)
print("result flatten")

print("Method 1 \n",np.concatenate([a,b],axis=1))
print("Method 2 \n",np.hstack([a,b]))
print("Method 3 \n",np.c_[a,b])




a :  [[0 1 2 3 4]
 [5 6 7 8 9]]
b :  [[1 1 1 1 1]
 [1 1 1 1 1]]
result flatten
Method 1 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Method 2 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Method 3 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [11]:
# 10. How to generate custom sequences in numpy without hardcoding?

# Difficulty Level: L2

# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input:

a = np.array([1,2,3])

# Desired Output:

# #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

aTile = np.tile(a,3)
aRepeat = np.repeat(a,3)
print("This using numpy Tile : ",aTile)
print("This using numpy repeat : ",aRepeat)
np.concatenate([aRepeat,aTile])




This using numpy Tile :  [1 2 3 1 2 3 1 2 3]
This using numpy repeat :  [1 1 1 2 2 2 3 3 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
# 11. How to get the common items between two python numpy arrays?

# Difficulty Level: L2

# Q. Get the common items between a and b

# Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:

# array([2, 4])
np.intersect1d(a,b)


array([2, 4])

In [13]:
# 12. How to remove from one array those items that exist in another?

# Difficulty Level: L2

# Q. From array a remove all items present in array b

# Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Desired Output:

# array([1,2,3,4])

np.setdiff1d(a,b)


array([1, 2, 3, 4])

In [14]:
# 13. How to get the positions where elements of two arrays match?

# Difficulty Level: L2

# Q. Get the positions where elements of a and b match

# Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:

# #> (array([1, 3, 5, 7]),)
np.where(a==b)


(array([1, 3, 5, 7], dtype=int64),)

In [15]:
# 14. How to extract all numbers between a given range from a numpy array?

# Difficulty Level: L2

# Q. Get all items between 5 and 10 from a.

# Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Desired Output:

# (array([6, 9, 10]),)
# Method 1
index = np.where(((a>=5) & (a<=10)))
a[index]

# Method 2
index = np.where(np.logical_and(a>=5,a<=10))
a[index]

# Method 3
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

In [16]:
# 15. How to make a python function that handles scalars to work on numpy arrays?

# Difficulty Level: L2

# Q. Convert the function maxx that works on two scalars, to work on two arrays.

# Input:

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)
#> 5

# Desired Output:

# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

# ============================ ANSWER ============================ #

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

def gt():
    start = time.time()
    start_cpu = time.process_time() 
    return start,start_cpu
# Original input
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1]

# experimental input
a = np.random.randint(0,1000,10**6)
b = np.random.randint(0,1000,10**6)

# print(a,"\n",b)

# ======== METHOD 1
print("Method 1 ")

st, stc = gt()
c=[]

for i in range(len(a)):
    result = maxx(a[i],b[i])
    c.append(result)

print(np.array(c,dtype=float)[:5])

et, etc = gt()
print('Execution time:', (et - st)*1000, 'miliseconds')
print('Execution CPU time:', (etc - stc)*1000, 'miliseconds')
print()
# ======== METHOD 2
print("Method 2 ")

st, stc = gt()
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a,b)[:5])

et, etc = gt()
print('Execution time:', (et - st)*1000, 'miliseconds')
print('Execution CPU time:', (etc - stc)*1000, 'miliseconds')

# using np.vectorize more faster
# syntax np.vectorize
# vectorize_funcunction = np.vectorize (function, parameter 1, parameter 2….. parameter N)
# vectorize func: return a new array from implementing the function


Method 1 
[849. 368. 921. 785. 348.]
Execution time: 3093.005418777466 miliseconds
Execution CPU time: 3031.25 miliseconds

Method 2 
[849. 368. 921. 785. 348.]
Execution time: 833.9958190917969 miliseconds
Execution CPU time: 828.125 miliseconds


In [17]:
# 16. How to swap two columns in a 2d numpy array?

# Difficulty Level: L2

# Q. Swap columns 1 and 2 in the array arr.

# arr = np.arange(9).reshape(3,3)
# arr

# ======================= ANSWER ======================= #
arr = np.arange(9).reshape(3,3)
arr[:,[2,0,1]] #  [: -> row, 0 1 2->is the position]

array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [18]:
# 17. How to swap two rows in a 2d numpy array?

# Difficulty Level: L2

# Q. Swap rows 1 and 2 in the array arr:

# arr = np.arange(9).reshape(3,3)
# arr

# ======================= ANSWER ======================= #
arr = np.arange(9).reshape(3,3)
arr[[1,2,0],:]


array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [19]:
# 18. How to reverse the rows of a 2D array?

# Difficulty Level: L2

# Q. Reverse the rows of a 2D array arr.

# # Input
# arr = np.arange(9).reshape(3,3)

# ================= ANSWER ================= # 
arr = np.arange(9).reshape(3,3)
print(arr)
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [20]:
# 19. How to reverse the columns of a 2D array?

# Difficulty Level: L2

# Q. Reverse the columns of a 2D array arr.

# # Input
# arr = np.arange(9).reshape(3,3)

# ================= ANSWER ================= # 
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [21]:
# 20. How to create a 2D array containing random floats between 5 and 10?

# Difficulty Level: L2

# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# ================= ANSWER ================= #
# input
st,stc = gt()
arr = np.arange(9).reshape(3,3)

arr_rand = np.random.randint(low=5,high=10,size=(5,3))
print(arr_rand)
arr_rand = np.random.randint(low=5,high=10,size=(5,3)) + np.random.random((5,3))
# np.random.random return float array
# print(arr_rand)
et, etc = gt()
print('Execution time:', (et - st)*1000, 'miliseconds')
print('Execution CPU time:', (etc - stc)*1000, 'miliseconds')

[[6 7 5]
 [8 6 5]
 [9 9 7]
 [7 5 6]
 [6 8 9]]
Execution time: 3.9992332458496094 miliseconds
Execution CPU time: 0.0 miliseconds


In [22]:
# 21. How to print only 3 decimal places in python numpy array?

# Difficulty Level: L1

# Q. Print or show only 3 decimal places of the numpy array rand_arr.

# Input:

# rand_arr = np.random.random((5,3))

rand_arr = np.random.random((5,3))
print(rand_arr)

rand_arr = np.random.random([5,3])
print(rand_arr)

np.set_printoptions(precision=3)
rand_arr[:4]

[[0.69905796 0.97178008 0.4669013 ]
 [0.3927246  0.73771523 0.598196  ]
 [0.24111008 0.04618302 0.46470177]
 [0.24979765 0.56403697 0.83824775]
 [0.28626282 0.81073831 0.04516971]]
[[0.13032889 0.09974563 0.66960257]
 [0.75854567 0.97865951 0.64285736]
 [0.51220493 0.1024678  0.55187981]
 [0.94077675 0.18618711 0.57614288]
 [0.95198835 0.5665044  0.58020487]]


array([[0.13 , 0.1  , 0.67 ],
       [0.759, 0.979, 0.643],
       [0.512, 0.102, 0.552],
       [0.941, 0.186, 0.576]])

In [23]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

# Difficulty Level: L1

# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input:

# # Create the random array
# np.random.seed(100)
# rand_arr = np.random.random([3,3])/1e3
# rand_arr

# #> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
# #>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
# #>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

# Desired Output:

# #> array([[ 0.000543,  0.000278,  0.000425],
# #>        [ 0.000845,  0.000005,  0.000122],
# #>        [ 0.000671,  0.000826,  0.000137]])


np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(precision=6,suppress=True)
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [25]:
# 23. How to limit the number of items printed in output of numpy array?

# Difficulty Level: L1

# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

# Input:

# a = np.arange(15)
# #> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Desired Output:

# #> array([ 0,  1,  2, ..., 12, 13, 14])
np.set_printoptions(threshold= 6)
np.arange(15)


array([ 0,  1,  2, ..., 12, 13, 14])

NumPy | set_printoptions method
https://www.skytowner.com/explore/numpy_set_printoptions_method#examples/specifying_edgeitems